name: unit testing

on:
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    name: "Run unit test case"
    runs-on: ubuntu-latest
    steps:
      - name: "checkout code"
        uses: actions/checkout@v3

      - name: "Run unit test case"
        run: |
          npm run test